### ISSUE TITLE
自訂辭典 在 cut_batch 和 pseg_batch function下沒有作用?

### ISSUE THREAD

**Issue by leo10816** [monpa-team/monpa#12]
在使用load_userdict讀取自訂辭典後發現
monpa.cut會根據辭典結果進行修正
但在使用 cut_batch 和 pseg_batch時
斷詞結果似乎沒有變化
請問現在還不支援嗎?

**Comment by windyeh** [comment]
cut_batch 及 pseg_batch 不支援自訂詞。

**Comment by windyeh** [comment]
as response, we don't have plan to include this till now.
