### ISSUE TITLE
About named entity recognition

### ISSUE THREAD

**Issue by ag027592** [monpa-team/monpa#15]
Hi, thanks for your sharing,

Can monpa extract named entity information?

**Comment by windyeh** [comment]
sure, you can use monpa.pseg function to get pos/ner, refer to [https://github.com/monpa-team/monpa#pseg-function](https://github.com/monpa-team/monpa#pseg-function)

for the specification of POS, NER that we are using, refer to [https://github.com/monpa-team/monpa/wiki/POS-and-NER-Tagging](https://github.com/monpa-team/monpa/wiki/POS-and-NER-Tagging)

**Comment by ag027592** [comment]
> sure, you can use monpa.pseg function to get pos/ner, refer to https://github.com/monpa-team/monpa#pseg-function
> 
> for the specification of POS, NER that we are using, refer to https://github.com/monpa-team/monpa/wiki/POS-and-NER-Tagging

Thanks for your reply.
