### ISSUE TITLE
How to dismiss message of " Welcome to MONPA: Multi-Objective NER POS Annotator for Chinese"

### ISSUE THREAD

**Issue by shilik** [monpa-team/monpa#18]
@windyeh 
Apache server的error log 都會出現以下的wsgi:error
在cli下執行雖然也會有同樣的字樣，但不會有錯誤。請教如何關掉這類的message使其不要出現wsgi:error？
謝謝

`[Wed Mar 06 12:13:47.823665 2024] [wsgi:error] [pid 6932] +---------------------------------------------------------------------+
[Wed Mar 06 12:13:47.823691 2024] [wsgi:error] [pid 6932]   Welcome to MONPA: Multi-Objective NER POS Annotator for Chinese
[Wed Mar 06 12:13:47.823694 2024] [wsgi:error] [pid 6932] +---------------------------------------------------------------------+
[Wed Mar 06 12:13:47.851108 2024] [wsgi:error] [pid 6932] \xe5\xb7\xb2\xe6\x89\xbe\xe5\x88\xb0 model\xe6\xaa\x94\xe3\x80\x82Found model file.
`

**Comment by windyeh** [comment]
```
+---------------------------------------------------------------------+
Welcome to MONPA: Multi-Objective NER POS Annotator for Chinese
+---------------------------------------------------------------------+
```
是提醒使用者已經正確啟用 monpa 套件。
如果不想出現，請到安裝 monpa 套件資料夾內以註解或是刪除 `__init__.py` 的 30 ~ 32 行。

要找到 python 環境內的 monpa 安裝套件位置，可以在 python 內試試：
```python
import monpa
print(monpa.__file__)
```
就會印出 `__init__.py`的位置。
