### ISSUE TITLE
jupyter notebook 的 import monpa 問題

### ISSUE THREAD

**Issue by wthomasu** [monpa-team/monpa#2]
PY新手請問

不好意思，請問一下，使用anaconda開啟的jupyter notebook沒辨法import monpa，使用dos指令開啟的jupyter notebook沒問題，謝謝

**Comment by windyeh** [comment]
或許您打開的是不同 python 環境下的 jupyter notebook，一個有安裝，一個沒安裝？

**Comment by ChiLunHuang** [comment]
I have the same issue about `import monpa` in python 3.5 and python2.7.
And the error message is:

<img width="820" alt="2019-07-29" src="https://user-images.githubusercontent.com/18207517/62037411-51a85b00-b226-11e9-91a0-8bca72455f62.png">

Any help would be greatly appreciated.

**Comment by windyeh** [comment]
Now, the monpa can be run in python >= 3.6 but not support python 2.x version.

**Comment by ChiLunHuang** [comment]
> Now, the monpa can be run in python >= 3.6 but not support python 2.x version.

Thanks for your reply. I will try in python 3.6 later!
