### ISSUE TITLE
how to run on gpu?

### ISSUE THREAD

**Issue by AskAQ** [monpa-team/monpa#4]
發現加入user_dict，
切分詞跑得很慢，
有提供可以跑在gpu的方法嗎?

**Comment by windyeh** [comment]
加自訂詞後會先比較篩出自訂詞再處理斷詞，所以會影響執行效率。我們的目標是做到盡量不需自訂詞，還需努力。
另外，關於使用 GPU 是一個好問題，也是一個複雜的問題。pytorch 開啟使用 GPU 很簡單，只要設定 device 使用 cuda ，再將 model 及處理資訊導入 cuda 即可。但是，如果沒有修改執行程序為一次導入大量資料到 cuda，卻還是使用原始一次一個處理程序，則執行效率會更慢。
一次導入大量資料到 cuda 的程式還在開發測試中，未來或許會出文件說明。

**Comment by AskAQ** [comment]
葉先生您好：

我目前是研究生，
欲研究在中文未知詞上的詞性標注，
但我survey過程中看到比較多的是用bert做ner
我目前也是用pytorch,
因為bert斷詞是一個字斷而不是一個詞斷，
這樣難以做到pos tagging,
想請教您在bert上如何實踐pos tagging的，
感謝您撥冗回答，
謝謝您

Wen-Chao Yeh <notifications@github.com> 於 2019年8月22日 週四 上午11:05 寫道：

**Comment by windyeh** [comment]
也是一個字一個字處理，雖然程式還沒放上 Github，但有 pip install monpa 就可以到 package 安裝處查看修改程式。至於被安裝到哪個資料夾，可以用 python 跑看看。
```python
import os
import monpa

os.path.abspath(monpa.__file__)

**Comment by windyeh** [comment]
隔了一段時間，但運用有限的資源，我們還是努力的開發利用 GPU 加速的功能，近期將會搭配說明文件一併釋出。
