### ISSUE TITLE
自訂辭典導致分詞出現重複詞

### ISSUE THREAD

**Issue by tingjhenjiang** [monpa-team/monpa#6]
example of user's dictionary
賣弄風騷的人 1000 NER
獨領世界風騷 1000 NER
獨領風騷 1000 NER
賣弄風騷 1000 NER
帶領風騷 1000 NER
領風騷 1000 NER
風騷 1000 NER

print(monpa.cut("15檔龍年雙旺領風騷"))
> ['15', '檔', '龍年', '雙', '旺領', '風騷']

monpa.load_userdict(file_path_to_dict)

print(monpa.cut("15檔龍年雙旺領風騷"))
> ['15', '檔', '龍年', '雙', '旺', '領風騷', '風騷']

============================================
example of user's 2nd dictionary (remove 風騷 1000 NER)
賣弄風騷的人 1000 NER
獨領世界風騷 1000 NER
獨領風騷 1000 NER
賣弄風騷 1000 NER
帶領風騷 1000 NER
領風騷 1000 NER

print(monpa.cut("15檔龍年雙旺領風騷"))
> ['15', '檔', '龍年', '雙', '旺領', '風騷']

monpa.load_userdict(file_path_to_dict)

print(monpa.cut("15檔龍年雙旺領風騷"))
> ['15', '檔', '龍年', '雙', '旺', '領風騷']

**Comment by windyeh** [comment]
Thank you, we will fix this by next release.

**Comment by windyeh** [comment]
new release (v0.2.5.1) is on the way, please feel free to try it.

**Comment by tingjhenjiang** [comment]
> 
> 
> new release (v0.2.5.1) is on the way, please feel free to try it.

Nice! problems solved! Thank you!
