### ISSUE TITLE
downloading model 404?

### ISSUE THREAD

**Issue by k123321141** [monpa-team/monpa#7]
http 404: http://nlp.tmu.edu.tw/monpa_model/model-511.pt

/monpa/__init__.py in <module>
     73     with open(path_model, 'wb') as f:
     74         r = requests.get(download_model_url, stream=True)
---> 75         total_length = int(r.headers.get('content-length'))
     76         print("Total  file  size:", total_length, "KB")
     77         dl = 0

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

I guess you have changed the link?

**Comment by windyeh** [comment]
Due to license issue, we just published a new version. Please upgrade by pip install to fetch new model.
